#!/bin/sh
#
# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-01-31
# License: MIT
# Version: 0.1.0 2021-01-31
#                Initial release, I am using it and it seems to do its thing
#
#
# This is a turn-key restore of a fresh iSH back to a useable state
#
# Works both on AppStor and TestFlight iSH
#
# copy it outside the iSH filesystem in order for it to survive a delete - install cycle
# I use mount -t ios . /mnt
# and then select a dir on iCloud, so I can get all my various device restored from the same source.
# But im sure there are other ways to do it.
#
# Any feedback / bug reports welcome!
#


#
#  Set to 0 if you dont want to generate ssh host keys
#  it does take a while...
#
do_ssh_host_keys=1

#
# Some stuff I don't want to put in githbub :)
# set it to empty if you don't need it.
#
extra_tasks=/mnt/bin/additional-restore-tasks


#
# Set theese if you want to restore home dirs
#
root_tgz=/mnt/root.tgz
home_tgz=/mnt/home.tgz




echo "===  Copying some files to /etc  ==="
cp /mnt/files/repositories /etc/apk
cp /mnt/files/hosts /etc
echo


echo "===  using Alpine 3.12 repository and doing upgrade  ==="
apk update
apk upgrade
echo


echo "===  Installing my selection of software  ==="
# I gathered theese leave nodes with apk-leaves (same repo)
apk add bash emacs-nox git joe mosh openssh rsync sudo tmux
echo


echo "===  Adding user(s) and activating sudo  ==="
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
adduser jaclu -D
addgroup jaclu wheel
echo


echo "===  Restoring home dirs  ==="
cd /
if [ -f $root_tgz ]; then
    echo -n "restoring /root ... "
    tar xfz $root_tgz
    echo "Done!"
fi
if [ -f $home_tgz ]; then
    echo -n "restoring /home ... "
    tar xfz $home_tgz
    echo "Done!"
fi
echo


if [ -x $extra_tasks ]; then
    echo "===  Running additional local restore tasks  ==="
    $extra_tasks
    echo
fi


if [ $do_ssh_host_keys -eq 1 ]; then
    echo "===  Generating host keys, will take a while...  ==="
    ssh-keygen -A
	echo
fi

echo
echo "All done, system is restored! You probably want to reboot to get envs as intended"
