#!/bin/sh
#
# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-02-21
# License: MIT
# Version: 0.1.0 2021-02-21
#                Initial release, I am using it and it seems to do its thing
#
#
# This is a turn-key restore of a fresh AOK iSH into a useable state
#
# Works both on AppStore and TestFlight iSH
#
# copy this outside the iSH filesystem in order for it to survive a delete - install cycle
# I use mount -t ios . /mnt
# Then select a dir on iCloud, so I can get all my various device restored from the same source.
# But im sure there are other ways to do it.
#
# Any feedback / bug reports welcome!
#


#
# Some stuff I don't want to put in githbub :)
# set it to empty if you don't need it, or the remove the code that uses it
#
extra_tasks=/mnt/bin/additional-restore-tasks


#
# Currently I just deploy one home dir
#
my_home_dirs=/mnt/jaclu.tgz




echo "===  Copying some files to /etc  ==="
# Add my local hosts, so I have my non DNS nodes easily accessable
# /etc/apk/repositories is alreay fine in AOK
cp /mnt/files/hosts /etc
echo


echo "===  doing update upgrade procedure  ==="
apk update
apk upgrade
echo


echo "===  Installing my selection of software  ==="
# I gathered theese leave nodes with apk-leaves (same repo)
apk add emacs-nox joe rsync zsh
echo


echo "===  Adding user(s) and activating sudo  ==="
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
adduser jaclu -D
addgroup jaclu wheel
echo


echo "===  Restoring home dirs  ==="
cd /home
if [ -f $my_home_dirs ]; then
    echo -n "restoring into /home ... "
    tar xfz $my_home_dirs
    echo "Done!"
fi
echo


if [ -x $extra_tasks ]; then
    echo "===  Running additional local restore tasks  ==="
    $extra_tasks
    echo
fi

echo
echo "All done, system is restored!"
