#!/bin/sh
#
# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-02-21
# License: MIT
_version=0.2.1
# Version: 0.2.1 2021-02-21
#                Added a lot of features, including sshd host keys if found.
#                Correctly identifies if the system is using AOK filesystem
#                And adjusts procedure accordingly
#          0.1.0 2021-01-31
#                Initial release, I am using it and it seems to do its thing
#
#
# This is a turn-key restore of a fresh iSH back to a useable state
#
# Works both on AppStore and TestFlight iSH
#
# copy it outside the iSH filesystem in order for it to survive a delete - install cycle
# I use mount -t ios . /mnt
# and then select a dir on iCloud, so I can get all my various device restored from the same source.
# But im sure there are other ways to do it.
#
# Any feedback / bug reports welcome!
#


#
# Set to 0 if you dont want to run sshd automatically
# at boot, this is ignored if this is a AOK filesystem
#
activate_sshd_service=0


#
# If empty no user env will be restored
#
my_uname="jaclu"


#
# Some stuff I don't want to put in githbub :)
# set it to empty if you don't need it.
#
extra_tasks=/mnt/bin/additional-restore-tasks


#
# Set theese if you want to restore home dirs
#
home_root=/mnt/files/tars/home_root.tgz
# a radnom something, indicating this has already been deployed
home_root_unpacked_ptr=/root/.local

home_mine=/mnt/files/tars/home_${my_uname}.tgz
# a radnom something, indicating this has already been deployed
home_mine_unpacked_ptr=/home/${my_uname}/.shell_envs_cfg



#==========================================================
#
#  Variables from here on are set by the system
#
#==========================================================


#
# Identifying current environ
#
this_host=$(hostname)

if [ -d /AOK ]; then
    FS='AOK'
    echo "Assuming this is an AOK file system"
else
    FS='iSH'
    echo "Assuming this is a regular iSH file system"
fi
echo




echo "===  Copying some files to /etc  ==="
# Add my local hosts
cp /mnt/files/hosts /etc
echo "---  /etc/hosts  ---"
if [ "$FS" != "AOK" ]; then
    # point to Alpine 3.12
    cp /mnt/files/repositories /etc/apk
    echo "---  /etc/apk/repositories  ---"

    # Get rid of unused getty's
    cp /mnt/files/inittab /etc
    echo "---  /etc/inittab  ---"
fi
echo


echo "===  update & upgrade  ==="
apk update && apk upgrade
if [ $? -ne 0 ]; then
    echo
    echo "ERROR: Failed to update repos - network issue?"
    echo
    exit 1
fi
echo


echo "===  Installing my selection of software  ==="
apk_instal_scr=/mnt/specifics/FS/${FS}/my_apks
if [ -x $apk_instal_scr ]; then
    $apk_instal_scr
else
    echo "*** Not found: $apk_instal_scr"
fi
echo


if [ "$FS" != "AOK" ]; then
    echo "===  Considering restoration of /root  ==="
    if [ "$home_root" != "" ]; then
        if [ "$home_root_unpacked_ptr" != "" ] && [ -r $home_root_unpacked_ptr ]; then
            echo "---   Seems like /root has been restored already   ---"
        else
            if [ -f "$home_root" ]; then
                echo "---   Found a tarball, unpacking it   ---"
                cd /
                tar xfz $home_root
            fi
        fi
    fi
    echo
fi


echo "===  Ensure no pw sudo for group wheel is active  ==="
grep restore-ish /etc/sudoers > /dev/null
if [ $? -eq 1 ]; then
    echo "---  adding %wheel NOPASSWD to /etc/sudoers  --"
    echo "%wheel ALL=(ALL) NOPASSWD: ALL # added by restore-ish" >> /etc/sudoers
fi
echo


if [ "$my_uname" != "" ]; then
    echo "===  Ensure user $my_uname has been created  ==="
    grep $my_uname /etc/passwd > /dev/null
    if [ $? -eq 1 ]; then
        echo "---  adding user $my_uname  --"
        adduser $my_uname -D
        # This adds no pw sudo
        addgroup $my_uname wheel
    fi
    echo


    echo "===  Considering restoration of /home/$my_uname  ==="
    if [ "$home_mine" != "" ]; then
        if [ "$home_mine_unpacked_ptr" != "" ] && [ -r $home_mine_unpacked_ptr ]; then
            echo "---   Seems like /home/$my_uname has been restored already   ---"
        else
            if [ -f "$home_mine" ]; then
                echo "---   Found a tarball, unpacking it   ---"
                cd /home
                tar xfz $home_mine
            fi
        fi
    fi
    echo
fi


echo "===  Unpacking sshd host keys for: $this_host  (if found)  ==="
sshd_host_keys=/mnt/specifics/${this_host}-sshd_host_keys.tgz
if [ -f "$sshd_host_keys" ]; then
    cd /etc/ssh
    tar xvfz $sshd_host_keys
fi
echo


if [ "$FS" != "AOK" ]; then
    if [ $activate_sshd_service -eq 1 ]; then
        echo "===  Generating host keys if not restored, might take a while...  ==="
        ssh-keygen -A
        echo

        echo "===  Setting up sshd as a service...  ==="
        apk add openrc
        rc-update add sshd
        echo
    fi
fi


if [ -x $extra_tasks ]; then
    echo "===  Running additional local restore tasks  ==="
    echo
    . $extra_tasks
    echo
else
    echo "===  No extra tasks requested  ==="
    echo
fi



echo
echo "All done, system is restored!"
