#!/bin/sh

#
# Simulating the restore-ish output style
#
function msg_2() {
    local msg=$1

    echo "=== $msg ==="
}

function msg_3() {
    local msg=$1

    echo "--- $msg ---"
}


msg_2 "Softlinking ~/cloud"
cd ~/
ln -sf /iCloud/cloud
echo
