#!/bin/sh
#
# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-04-13
# License: MIT



task_location_tracker() {
    if [ "$1" != "" ]; then
	activate_location_tracker=$1
    elif [ "$IT_LOCATION_SERVICE" != "" ]; then
	activate_location_tracker=$IT_LOCATION_SERVICE
    else
	error_msg "IT_LOCATION_SERVICE not defined, asuming no action"
    fi
    msg_txt="location_tracker service"
    msg2_txt="  Ensuring iSH continues to run in the background."
    case "$activate_location_tracker" in
        -1 ) # disable
	    msg_2 "$msg_txt"
    	    echo "$msg2_txt"
            msg_3 "will be disabled"
            if [ ! "$IT_TASK_DISPLAY" = "1" ]; then			
                if [ "$(2> /dev/null rc-status |grep location_tracker)" != "" ]; then
		    rc-service location_tracker stop
        	    rc-update del location_tracker
		    msg_3 "was disabled"
                else
                    echo "location_tracker not active, no action needed"
                fi
		rm /etc/init.d/location_tracker 2> /dev/null
            fi
            ;;
        0 )  # unchanged
            if [ "$IT_TASK_DISPLAY" = "1" ] &&  [ "$IT_DISPLAY_NON_TASKS" = "1" ]; then
		msg_2 "$msg_txt"
                echo "Will NOT be changed"
            fi

            ;;
	
        1 )  # activate 
    	    msg_2 "$msg_txt"
    	    echo "$msg2_txt"
	    service_file=/etc/init.d/location_tracker
            if [ "$IT_TASK_DISPLAY" = "1" ]; then
		msg_3 "Will be enabled"
	    else	
		ensure_runlevel_default
		if [ ! -f "$service_file" ]; then
		    # do this after 'ensure_runlevel_default', to be sure
		    # openrc has been installed, thus creating the dest
		    # dir for the service_file being copied into place
		    cp -av $DEPLOY_PATH/files/init.d-location_tracker "$service_file"
		    chmod 755 "$service_file"
		fi
		ensure_service_is_added location_tracker restart
            fi
            ;;
        *)
            error_msg "Invalid setting: activate_location_tracker=$activate_location_tracker\nValid options: -1 0 1" 1
    esac
    echo
}


if test -z "$DEPLOY_PATH" ; then
    # Most likely not sourced...
    DEPLOY_PATH="$(dirname "$0")/.."               # relative
    DEPLOY_PATH="$( cd "$DEPLOY_PATH" && pwd )"  # absolutized and normalized
fi
. "$DEPLOY_PATH/scripts/extras/utils"
. "$DEPLOY_PATH/scripts/extras/openrc"



#==========================================================
#
#     Not sourced main
#
#==========================================================
if [ "$IT_INITIAL_SCRIPT" = "" ]; then
    # Since sourced mode cant be detected in a practiacl way under ash,
    # I use this workaround
    IT_INITIAL_SCRIPT=1
    
    case "$1" in
	"-?"|"-h"|"--help")
	    echo "Env paramas"
	    echo "IT_LOCATION_SERVICE$(test -z "$IT_LOCATION_SERVICE" && echo ' -  location_tacker status (-1/0/1)' || echo =$IT_LOCATION_SERVICE)"
	    echo "IT_TASK_DISPLAY$(test -z "$IT_TASK_DISPLAY" && echo ' -  if 1 will only display what will be done' || echo =$IT_TASK_DISPLAY)"
	    echo "IT_DISPLAY_NON_TASKS$(test -z "$IT_DISPLAY_NON_TASKS" && echo ' -  if 1 will show what will NOT happen' || echo =$IT_DISPLAY_NON_TASKS)"
	    ;;
	*)
	    test -z "$1" || IT_LOCATION_SERVICE="$1"
	    task_location_tracker $IT_LOCATION_SERVICE
    esac
fi
