#!/bin/sh
#
# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-04-13
# License: MIT


task_nopasswd_sudo() {
    msg_2 "no-pw sudo for group wheel"
    if [ "$IT_TASK_DISPLAY" != "1" ]; then
        ensure_installed sudo
        grep restore-ish /etc/sudoers > /dev/null
        if [ $? -eq 1 ]; then
            msg_3 "adding %wheel NOPASSWD to /etc/sudoers"
            echo "%wheel ALL=(ALL) NOPASSWD: ALL # added by restore-ish" >> /etc/sudoers
        else
            msg_3 "pressent"
        fi
    elif [ "$IT_DISPLAY_NON_TASKS" = "1" ]; then
	echo "Will NOT be set"
    else
	echo "will be set if not done already"
    fi
    echo
}





if test -z "$DEPLOY_PATH" ; then
    # Most likely not sourced...
    DEPLOY_PATH="$(dirname "$0")/.."               # relative
    DEPLOY_PATH="$( cd "$DEPLOY_PATH" && pwd )"  # absolutized and normalized
fi
. "$DEPLOY_PATH/scripts/extras/utils"


#==========================================================
#
#     Not sourced main
#
#==========================================================
if [ "$IT_INITIAL_SCRIPT" = "" ]; then
    # Since sourced mode cant be detected in a practiacl way under ash,
    # I use this workaround
    IT_INITIAL_SCRIPT=1

    case "$1" in
	"-?"|"-h"|"--help")
	    echo "Env paramas"
	    echo "IT_APKS_DEL$(test -z "$IT_APKS_DEL" && echo ' - packages to remove' || echo =$IT_APKS_DEL )"
	    echo "IT_APKS_ADD$(test -z "$IT_APKS_ADD" && echo ' - packages to add' || echo =$IT_APKS_ADD )"

	    
	    echo "IT_TASK_DISPLAY$(test -z "$IT_TASK_DISPLAY" && echo ' -  if 1 will only display what will be done' || echo =$IT_TASK_DISPLAY)"
	    echo "IT_DISPLAY_NON_TASKS$(test -z "$IT_DISPLAY_NON_TASKS" && echo ' -  if 1 will show what will NOT happen' || echo =$IT_DISPLAY_NON_TASKS)"
	    ;;
	*)
	    test -z "$1" || IT_TIME_ZONE="$1"
	    task_timezone
    esac
fi


